# Create Jenkins Pod in with label jenkins-slave-label  (in Jenkins\configuration\Kubernates)
#
apiVersion: v1
kind: Pod
metadata:
  name: k8s-webapp-build-pod
spec:
  imagePullSecrets:
  - name: regcred

  containers:
  - name: maven
    image: maven:alpine
    command:
    - cat
    tty: true
    resources:
      requests:
        cpu: 10m
 
  - name: docker 
    image: docker
    command:
    - cat     
    tty: true    
    volumeMounts: 
        - name: docker-storage 
          mountPath: /var/run  
    resources:
      requests:
        cpu: 10m

  - name: kubectl
    command:
    - cat     
    tty: true  
    image: lachlanevenson/k8s-kubectl
    resources:
      requests:
        cpu: 10m

  volumes: 
    - name: docker-storage 
      hostPath: 
        path: /var/run      
        

#kubectl create secret docker-registry regcred --docker-username=astoupin --docker-password=3472Ans123 --docker-server=docker.io     
     
 