apiVersion: v1
kind: Pod
metadata:
  name: k8s-webapp
  labels:
    app: k8s-webapp
spec:

  containers:
  - name: maven
    image: maven:alpine
    command:
    - cat
    tty: true

    
  - name: k8s-webapp
    image: astoupin/k8s-webapp
    tty: true

  - name: kubectl
    image: lachlanevenson/k8s-kubectl:v1.8.8
    command:
    - cat
    tty: true   

  imagePullSecrets:
  - name: regcred

#kubectl create secret docker-registry regcred --docker-username=astoupin --docker-password=3472Ans123 --docker-server=docker.io     
     
 