apiVersion: v1
kind: Pod
metadata:
  name: k8s-webapp
  labels:
    app: k8s-webapp
spec:
  imagePullSecrets:
  - name: regcred

  containers:
  - name: maven
    image: maven:alpine
    command:
    - cat
    tty: true
    
  - name: docker 
    image: docker
    command:
    - cat     
    tty: true    
    volumeMounts: 
        - name: docker-storage 
          mountPath: /var/run  

  #- name: k8s-webapp
  #  image: astoupin/k8s-webapp

  volumes: 
    - name: docker-storage 
      hostPath: 
        path: /var/run      
        

#kubectl create secret docker-registry regcred --docker-username=astoupin --docker-password=3472Ans123 --docker-server=docker.io     
     
 