apiVersion: apps/v1
kind: Deployment
metadata:
   name: wildfly
spec:
  selector:
    matchLabels:
      app: wildfly   
  replicas: 1
  template:
    metadata:
      labels:
        app: wildfly
    spec:
      containers:
      - name: wildfly
        image: bangnab/wildfly-oraclejdk
        ports:
        - containerPort: 80


